name: CI for Dev Branch

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Tests in Repo A
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: jain-sumit-tft/Automation-exercise-Livelike  # Replace with your Repo A's name
          event-type: run-tests
          token: ${{ secrets.GITHUB_TOKEN }}
