name: CI for Dev Branch

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to trigger repository_dispatch in another repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Trigger Tests in Repo A
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: jain-sumit-tft/Automation-exercise-Livelike  # Replace with your Repo A's name
          event-type: run-tests
          token: ${{ secrets.GITHUB_TOKEN }}
